### ISSUE TITLE
Support encrypted EBS

### ISSUE THREAD

**Issue by Ruby202308** [VeeamHub/veeam-aws-cloudformation#3]
My company has security compliance that’s all EBS are encrypted. It would be wonderful if the cloud formation template supports encrypted EBS.

**Comment by ericellenberg** [comment]
@Ruby202308 - The templates in this repo do not deploy EC2 or EBS resources. Can you provide more details on this issue as it pertains to this project?

**Comment by Ruby202308** [comment]
Hi, I thought it is the Installing Veeam Backup for AWS Using
CloudFormation Template. Is there any way to update the cloud formations
template with encrypted EBS?

**Comment by couplebits** [comment]
Hi @Ruby202308 - This project doesn't deploy Veeam Backup for AWS. Please share your request to the Veeam R&D forums. The Veeam Backup for AWS forum is here: [https://forums.veeam.com/veeam-backup-for-aws-f55/](https://forums.veeam.com/veeam-backup-for-aws-f55/)
