### ISSUE TITLE
ControlTower::Guard::Hook HOOK_COMPLETE_FAILED

### ISSUE THREAD

**Issue by jacido** [VeeamHub/veeam-aws-cloudformation#4]
**Describe the bug**

Greetings, I saw that when a customer followed the instructions on how to deploy the solution with the [user guide](https://helpcenter.veeam.com/docs/vbaws/guide/install_vb_cloudformation.html?ver=70) it had resulted in the error below:
_______________
Hook failed with message: ValidationError 
        [CT.EC2.PR.19]: Require an EC2 instance to use an AWS Nitro instance type that supports encryption in-transit between instances when created using the AWS::EC2::Instance resource type
        [FIX]: Set 'InstanceType' to an EC2 instance type based on the AWS Nitro system that supports encryption in-transit between instances.
_______________
CREATE_FAILED: The following hook(s) failed: [ControlTower::Guard::Hook]
_______________

They were using a T3 Virtualized instance built on the AWS Nitro System [link](https://docs.aws.amazon.com/ec2/latest/instancetypes/ec2-nitro-instances.html) resulting in a HOOK_COMPLETE_FAILED for the ControlTower::Guard::Hook. The error appears to be a false positive. Could you please advise what the issue may be?

**Comment by ericellenberg** [comment]
Hi @jacido - This project and repo does not contain the CloudFormation template that deploys Veeam Backup for AWS from the AWS Marketplace. Please report this specific issue to Veeam Support for further review. 

Note, there are multiple deployment options, and you can deploy via AMI as well. Reference: https://helpcenter.veeam.com/docs/vbaws/guide/install_vb_ami.html

Again, please report the issue to Veeam Support to have our QA review. Thanks!
